version: "3.8"

services:
  trakt-to-letterboxd:
    container_name: trakt-to-letterboxd
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LETTERBOXD_USERNAME=${LETTERBOXD_USERNAME}
      - LETTERBOXD_PASSWORD=${LETTERBOXD_PASSWORD}
      - TRAKT_USERNAME=${TRAKT_USERNAME}
