services:
  trakt-to-letterboxd:
    image: liamnou/trakt-to-letterboxd:latest
    container_name: trakt-to-letterboxd
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LETTERBOXD_USERNAME=${LETTERBOXD_USERNAME}
      - LETTERBOXD_PASSWORD=${LETTERBOXD_PASSWORD}
      - TRAKT_USERNAME=${TRAKT_USERNAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
